site_name: Myfirebase docs

theme_dir: 'mkdocs-material/material'

repo_name: myfirebase/myfirebase
repo_url: https://github.com/myfirebase/myfirebase

pages:

- Welcome: index.md

- Getting Started:
    - 'Installation': 'installation.md'
    - 'Directory Structure': 'directory-structure.md'

- The Basics:
    - "Components": 'components.md'
    - "Routing": 'routing.md'
    - "State Managment System": 'store.md'

- Managing SCSS/SASS:
    - 'Material design and SASS/SCSS': 'style.md'

- Functionalities: 
    - 'Authentication': 'authentication.md'
    - 'Cloud Storage': 'storage.md'
    - 'Cloud Functions': 'cloud-functions.md'
    - 'Cloud Messaging': 'cloud-messaging.md'

- Deep Dive:
    - 'Middlewares (Global Navigation guards)': 'global-guard.md'
    - 'Firebase Admin (Feature request)': 'admin.md'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

site_favicon: 'img/favicon.ico'

extra:
  logo: 'img/MyFireBase.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
